name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # این یعنی هر وقت روی شاخه main چیزی پوش شد، اجرا شود

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Azure via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # رفتن به پوشه پروژه در سرور
            cd my-resume-site
            
            # دریافت آخرین تغییرات از گیت‌هاب
            git pull origin main
            
            # ساخت مجدد ایمیج داکر (با تغییرات جدید)
            sudo docker build -t resume-app .
            
            # توقف و حذف کانتینر قدیمی (اگر وجود داشته باشد)
            sudo docker stop my-website || true
            sudo docker rm my-website || true
            
            # اجرای کانتینر جدید
            sudo docker run -d -p 80:80 --restart always --name my-website resume-app